# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
